// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm6KoCrnHV83qWvHc5X02iTTBuk7cmg2w',
    appId: '1:23623182966:web:ad9379e3afa2213d21cd57',
    messagingSenderId: '23623182966',
    projectId: 'libraryprofile-aacfd',
    authDomain: 'libraryprofile-aacfd.firebaseapp.com',
    storageBucket: 'libraryprofile-aacfd.firebasestorage.app',
    measurementId: 'G-LWWVYXE4NL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTVaEpdk8P1iTIKPuJSfCg9DA_bL9sPD4',
    appId: '1:23623182966:android:dd5b5897d910622921cd57',
    messagingSenderId: '23623182966',
    projectId: 'libraryprofile-aacfd',
    storageBucket: 'libraryprofile-aacfd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBx8cqi88pVsA1DAJRfhg7t6zAbQcT11eE',
    appId: '1:23623182966:ios:aebd03e8b1377a0921cd57',
    messagingSenderId: '23623182966',
    projectId: 'libraryprofile-aacfd',
    storageBucket: 'libraryprofile-aacfd.firebasestorage.app',
    iosClientId: '23623182966-r3mi6biadrsu6g7gdrbbl33d9fo1fm4g.apps.googleusercontent.com',
    iosBundleId: 'com.example.loopx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBx8cqi88pVsA1DAJRfhg7t6zAbQcT11eE',
    appId: '1:23623182966:ios:aebd03e8b1377a0921cd57',
    messagingSenderId: '23623182966',
    projectId: 'libraryprofile-aacfd',
    storageBucket: 'libraryprofile-aacfd.firebasestorage.app',
    iosClientId: '23623182966-r3mi6biadrsu6g7gdrbbl33d9fo1fm4g.apps.googleusercontent.com',
    iosBundleId: 'com.example.loopx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCm6KoCrnHV83qWvHc5X02iTTBuk7cmg2w',
    appId: '1:23623182966:web:673dcff6ce5f943421cd57',
    messagingSenderId: '23623182966',
    projectId: 'libraryprofile-aacfd',
    authDomain: 'libraryprofile-aacfd.firebaseapp.com',
    storageBucket: 'libraryprofile-aacfd.firebasestorage.app',
    measurementId: 'G-X734JFHFQB',
  );
}
